version: "3.0"

services:
  api:
    container_name: "api"
    volumes:
      - ./app :/app
    build: .
    ports:
      - 8080:8080
    depends_on:
      - kvs

  kvs:
    image: redis:7.0.5-alpine
    environment:
      TZ: 'Asia/Tokyo'
    ports:
      - "6379:6379"
    volumes:
      - redis_store:/data"
    tty: true

volumes:
  redis_store: