version: "3.0"

services:
  api:
    container_name: "api"
    volumes:
      - ./app :/app
    build: .
    ports:
      - 8080:8080
    depends_on:
      - kvs

  kvs:
    image: redis:7.0.5-alpine
    environment:
      TZ: 'Asia/Tokyo'
    ports:
      - "6379:6379"
    volumes:
      - redis_store:/data"
    tty: true

  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: password
    command: server --console-address ":9001" /data
    volumes:
    - ./minio_data:/export  # MinIOストレージの永続化
    ports:
      - 9000:9000
      - 9001:9001
  
  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'
    container_name: "rabbitmq"
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - 5672:5672
      - 15672:15672

volumes:
  redis_store: