# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class GetItems200Response(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    GetItems200Response - a model defined in OpenAPI

        item_id: The item_id of this GetItems200Response [Optional].
        q: The q of this GetItems200Response [Optional].
    """

    item_id: Optional[int] = Field(alias="item_id", default=None)
    q: Optional[str] = Field(alias="q", default=None)

GetItems200Response.update_forward_refs()
