# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class Post(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Post - a model defined in OpenAPI

        title: The title of this Post.
        text: The text of this Post [Optional].
    """

    title: str = Field(alias="title")
    text: Optional[int] = Field(alias="text", default=None)

    @validator("title")
    def title_min_length(cls, value):
        assert len(value) >= 2
        return value

    @validator("title")
    def title_max_length(cls, value):
        assert len(value) <= 10
        return value

    @validator("text")
    def text_max(cls, value):
        assert value <= 10
        return value

    @validator("text")
    def text_min(cls, value):
        assert value >= 2
        return value

Post.update_forward_refs()
